// mockProducts

import { Timestamp } from 'firebase/firestore';
import { Product } from 'types/data';

export const tableTitle = [
  { id: 'id', label: 'ID', width: '8%' },
  { id: 'item', label: 'ITEM', width: '34%' },
  { id: 'cantidad', label: 'CANTIDAD', width: '12%' },
  { id: 'precioUnitario', label: 'PRECIO UNIT', width: '12%' },
  { id: 'descuento', label: 'DESCUENTO', width: '11%' },
  { id: 'precioTotal', label: 'PRECIO TOTAL', width: '14%' },
  { id: 'accion', label: 'ACCION', width: '9%' },
];

export const mockProducts: Product[] = [
  {
    id: '101',
    name: 'Laptop HP X200',
    description: 'Laptop HP X200 con procesador Intel i7 y 16GB de RAM.',
    stock: {
      current: 35,
      minStock: 5,
      maxStock: 50,
      noPhysicalStock: false,
    },
    category: 'Electrónica',
    subCategory: 'Laptops',
    barcode: '987654321000',
    brand: 'HP',
    stockOwner: 'Proveedor A',
    weight: 1.5,
    storePosition: 'A1',
    providerProductCode: [{ id: 101, name: 'HPX200' }],
    specifications: [
      { title: 'Pantalla', description: '15.6 pulgadas Full HD' },
    ],
    variants: [{ color: 'Negro', barCode: '987654321000', stock: 35 }],
    prices: {
      cost: { value: 800 },
      retail: { value: 1000 },
      online: { value: 950 },
      mayo1: { value: 900 },
      mayo2: { value: 870 },
      mayo3: { value: 860 },
      mayo4: { value: 850 },
      reseller: { value: 920 },
    },
    internalId: 101,
    imageURL: ['https://example.com/laptop_hp_x200.jpg'],
    createdAt: new Date() as Timestamp,
    updatedAt: new Date() as Timestamp,
    showInStore: true,
    userFeedback: [{ id: 1, comment: 'Excelente rendimiento', rating: 5 }],
  },
  {
    id: '102',
    name: 'Smartphone Samsung Galaxy S21',
    description: 'Smartphone Samsung Galaxy S21 con cámara de 108MP.',
    stock: {
      current: 50,
      minStock: 10,
      maxStock: 100,
      noPhysicalStock: false,
    },
    category: 'Electrónica',
    subCategory: 'Smartphones',
    barcode: '123456789001',
    brand: 'Samsung',
    stockOwner: 'Proveedor B',
    weight: 0.3,
    storePosition: 'B2',
    providerProductCode: [{ id: 102, name: 'SGS21' }],
    specifications: [
      { title: 'Pantalla', description: '6.2 pulgadas Dynamic AMOLED' },
    ],
    variants: [{ color: 'Blanco', barCode: '123456789001', stock: 50 }],
    prices: {
      cost: { value: 500 },
      retail: { value: 800 },
      online: { value: 750 },
      mayo1: { value: 720 },
      mayo2: { value: 710 },
      mayo3: { value: 695 },
      mayo4: { value: 680 },
      reseller: { value: 730 },
    },
    internalId: 102,
    imageURL: ['https://example.com/samsung_galaxy_s21.jpg'],
    createdAt: new Date() as Timestamp,
    updatedAt: new Date() as Timestamp,
    showInStore: true,
    userFeedback: [{ id: 2, comment: 'Gran cámara y desempeño', rating: 4 }],
  },
  {
    id: '103',
    name: 'Tableta Apple iPad Pro',
    description: 'Tableta Apple iPad Pro de 12.9 pulgadas con chip M1.',
    stock: {
      current: 20,
      minStock: 5,
      maxStock: 30,
      noPhysicalStock: false,
    },
    category: 'Electrónica',
    subCategory: 'Tablets',
    barcode: '234567890002',
    brand: 'Apple',
    stockOwner: 'Proveedor C',
    weight: 0.6,
    storePosition: 'C3',
    providerProductCode: [{ id: 103, name: 'IPADPRO12' }],
    specifications: [
      { title: 'Pantalla', description: '12.9 pulgadas Liquid Retina' },
    ],
    variants: [{ color: 'Gris Espacial', barCode: '234567890002', stock: 20 }],
    prices: {
      cost: { value: 900 },
      retail: { value: 1100 },
      online: { value: 1050 },
      mayo1: { value: 1020 },
      mayo2: { value: 1000 },
      mayo3: { value: 980 },
      mayo4: { value: 960 },
      reseller: { value: 1040 },
    },
    internalId: 103,
    imageURL: ['https://example.com/apple_ipad_pro.jpg'],
    createdAt: new Date() as Timestamp,
    updatedAt: new Date() as Timestamp,
    showInStore: true,
    userFeedback: [{ id: 3, comment: 'Pantalla impresionante', rating: 5 }],
  },
  {
    id: '104',
    name: 'Auriculares Sony WH-1000XM4',
    description: 'Auriculares Sony con cancelación de ruido.',
    stock: {
      current: 15,
      minStock: 3,
      maxStock: 25,
      noPhysicalStock: false,
    },
    category: 'Electrónica',
    subCategory: 'Audio',
    barcode: '345678901003',
    brand: 'Sony',
    stockOwner: 'Proveedor D',
    weight: 0.3,
    storePosition: 'D4',
    providerProductCode: [{ id: 104, name: 'WH1000XM4' }],
    specifications: [
      { title: 'Tecnología', description: 'Cancelación de ruido adaptativa' },
    ],
    variants: [{ color: 'Negro', barCode: '345678901003', stock: 15 }],
    prices: {
      cost: { value: 200 },
      retail: { value: 350 },
      online: { value: 320 },
      mayo1: { value: 310 },
      mayo2: { value: 300 },
      mayo3: { value: 290 },
      mayo4: { value: 280 },
      reseller: { value: 310 },
    },
    internalId: 104,
    imageURL: ['https://example.com/sony_wh1000xm4.jpg'],
    createdAt: new Date() as Timestamp,
    updatedAt: new Date() as Timestamp,
    showInStore: true,
    userFeedback: [{ id: 4, comment: 'Sonido increíble y confort', rating: 5 }],
  },
  {
    id: '105',
    name: 'Monitor Dell UltraSharp U2720Q',
    description: 'Monitor 4K de 27 pulgadas Dell UltraSharp U2720Q.',
    stock: {
      current: 10,
      minStock: 2,
      maxStock: 20,
      noPhysicalStock: false,
    },
    category: 'Electrónica',
    subCategory: 'Monitores',
    barcode: '456789012004',
    brand: 'Dell',
    stockOwner: 'Proveedor E',
    weight: 4.5,
    storePosition: 'E5',
    providerProductCode: [{ id: 105, name: 'U2720Q' }],
    specifications: [
      { title: 'Resolución', description: '3840 x 2160 4K UHD' },
    ],
    variants: [{ color: 'Negro', barCode: '456789012004', stock: 10 }],
    prices: {
      cost: { value: 400 },
      retail: { value: 700 },
      online: { value: 650 },
      mayo1: { value: 630 },
      mayo2: { value: 610 },
      mayo3: { value: 600 },
      mayo4: { value: 590 },
      reseller: { value: 620 },
    },
    internalId: 105,
    imageURL: ['https://example.com/dell_u2720q.jpg'],
    createdAt: new Date() as Timestamp,
    updatedAt: new Date() as Timestamp,
    showInStore: true,
    userFeedback: [
      { id: 5, comment: 'Excelente resolución y colores', rating: 4 },
    ],
  },
  // Otros productos con nombres, precios, y códigos de barras diferentes
];
export const productColumns = [
  { id: 'id', label: 'ID', width: '10%' },
  { id: 'name', label: 'ITEM', width: '34%' },
  { id: 'quantity', label: 'CANTIDAD', width: '10%' },
  { id: 'unitPrice', label: 'PRECIO UNIT', width: '12%' },
  { id: 'discount', label: 'DESCUENTO', width: '11%' },
  { id: 'totalPrice', label: 'PRECIO TOTAL', width: '14%' },
  { id: 'action', label: 'ACCION', width: '9%' },
];
