import { Product } from 'types/data';

export const data: Product[] = [
    {
        dimensions: {
            height: 0.5,
            width: 20,
            depth: 10,
        },
        prices: {
            list: { value: 320 },
            web: { value: 250 },
            cash: { value: 300 },
            cost: {
                value: 176,
                lastModified: new Date('2023-01-06T20:12:26.297Z'),
            },
        },
        stock: 99972,
        weight: 0.5,
        storePosition: 'Repisa',
        description: 'Abrochadora Start #10 pulsador largo 15 hojas',
        internalId: 219,
        name: 'Abrochadora Deli E0260 Deli Vivid N°10',
        category: 'No se',
        image: '',
        barcode: '6921734902603',
        storeBranch: 'Av Belgrano 2848',
        storeId: '6053adb8a6b58a6e35dd4655',
        createdAt: new Date('2022-06-16T14:36:08.426Z'),
        updatedAt: new Date('2023-03-28T23:22:14.071Z'),
        brand: 'Deli',
        businessOwner: 'Mundo Regalo',
        providerProductCode: [
            {
                id: 111,
                name: 'San pablo',
            },
        ],
        specifications: [],
        variants: [],
    },
    {
        dimensions: {
            height: 0,
            width: 0,
            depth: 0,
        },
        prices: {
            list: { value: 4650.39 },
            web: { value: 3917.45 },
            cash: { value: 4420 },
            cost: {
                value: 2527.39,
                lastModified: new Date('2023-01-13T21:18:55.638Z'),
            },
        },
        stock: 0,
        weight: 0,
        storePosition: '0',
        description:
            'Nuestra pinza tiene un diseño sólido y dinámico, está compuesta de piezas estampadas en chapa de acero de primera calidad, las cuales no presentan bordes con filos ni ángulos que puedan provocar molestias al usuario. El Cargador, pieza donde se colocan los broches posee un frente cerrado que permite un abrochado perfecto aún en máximas exigencias. Además posee una base templada que asegura su buen funcionamiento. A lo largo de más de 30 años de trayectoria y a través de un estudio desarrollado de su rendimiento podemos afirmar que la Pinza es Confiable. Éste producto tiene un mecanismo simple, con escasas piezas móviles y su forma anátomica permite un uso suave y efectivo. Por su escaso peso que varía entre 200 y 250 gramos según la medida de la pinza y su armonica estructura evita la fatiga en el empleo intensivo. La alimentación es de carga simple, ya que no es necesario abrir la pinza y brinda tiempo al usuario en su acelerado ritmo de trabajo. La abrochadora se presenta pintada con pintura epoxi (Sistema de protección de larga duración) en varios colores, que asegura durabilidad y garantia de calidad. Bajo éstas condiciones logramos un producto competitivo tanto en el orden nacional como el internacional, presentando significativas ventajas respecto a otras máquinas similares.',
        internalId: 224,

        name: 'Abrochadora Grap 10/50 Pinza',
        category: 'libreria',
        image: '',
        barcode: '7798006055058',
        storeBranch: 'Av Belgrano 2848',
        storeId: '6053adb8a6b58a6e35dd4655',
        createdAt: new Date('2022-06-16T15:50:27.616Z'),
        updatedAt: new Date('2023-02-21T03:47:12.087Z'),
        brand: 'Grap',
        businessOwner: 'Mundo Regalo',
        providerProductCode: [],
        specifications: [
            {
                title: 'Broches Utilizados',
                description: '10/50',
            },
        ],
        variants: [],
        subCategory: 'Abrochadoras',
    },
    {
        dimensions: {
            height: 0,
            width: 0,
            depth: 0,
        },
        prices: {
            list: { value: 5529.2 },
            web: { value: 4657.75 },
            cash: { value: 5260 },
            cost: {
                value: 3005,
                lastModified: new Date('2023-01-13T21:18:01.688Z'),
            },
        },
        stock: 0,
        weight: 0,
        storePosition: 'Repisa',
        description: 'Abrochadora',
        internalId: 223,

        name: 'Abrochadora Grap 21/6 Pinza',
        category: 'libreria',
        image: '',
        barcode: '7798006055096',
        storeBranch: 'Av Belgrano 2848',
        storeId: '6053adb8a6b58a6e35dd4655',
        createdAt: new Date('2022-06-16T15:49:56.862Z'),
        updatedAt: new Date('2023-02-21T03:47:12.087Z'),
        brand: 'Grap',
        businessOwner: 'Mundo Regalo',
        providerProductCode: [],
        specifications: [],
        variants: [],
    },
    {
        dimensions: {
            height: 0,
            width: 0,
            depth: 0,
        },
        prices: {
            list: { value: 5911.41 },
            web: { value: 4979.716 },
            cash: { value: 5620 },
            cost: {
                value: 3212.72,
                lastModified: new Date('2023-01-13T21:16:58.533Z'),
            },
        },
        stock: 0,
        weight: 0,
        storePosition: 'Repisa',
        description: 'Abrochadora',
        internalId: 225,

        name: 'Abrochadora Grap 24/6 Pinza',
        category: 'libreria',
        image: '',
        barcode: '7798006050305',
        storeBranch: 'Av Belgrano 2848',
        storeId: '6053adb8a6b58a6e35dd4655',
        createdAt: new Date('2022-06-16T15:51:03.245Z'),
        updatedAt: new Date('2023-02-21T03:47:12.087Z'),
        brand: 'Grap',
        businessOwner: 'Mundo Regalo',
        providerProductCode: [],
        specifications: [],
        variants: [],
    },
    {
        dimensions: {
            height: 0,
            width: 0,
            depth: 0,
        },
        prices: {
            list: { value: 7405.86 },
            web: { value: 6230.5 },
            cash: { value: 7030 },
            cost: {
                value: 4019.68,
                lastModified: new Date('2023-01-13T21:51:35.803Z'),
            },
        },
        stock: 0,
        weight: 0,
        storePosition: 'Repisa',
        description:
            ' Utiliza Broches MIT 50 o Broches MIT 10  Abrocha de 1 a 20 hojas (Br. 50)  Su profundidad máxima de abrochado es de 45mm  Puede utilizarse como clavadora (abierta)  Estructura metálica (máxima durabilidad)  Recubierta con pintura epoxi, niquel y zinc  Diseñada para uso intenso en comercios, oficinas y el hogar',
        internalId: 222,

        name: 'Abrochadora MIT FX50 Pinza',
        category: 'libreria',
        image: '',
        barcode: '7793928100244',
        storeBranch: 'Av Belgrano 2848',
        storeId: '6053adb8a6b58a6e35dd4655',
        createdAt: new Date('2022-06-16T15:38:02.186Z'),
        updatedAt: new Date('2023-02-21T03:47:12.087Z'),
        brand: 'MIT',
        businessOwner: 'Mundo Regalo',
        providerProductCode: [
            {
                id: 15804,
                name: 'Libreria San Pablo',
            },
        ],
        specifications: [],
        subCategory: 'Abrochadoras / Broches',
        variants: [],
    },
];
