name: Bump version
on:
  push:
    branches:
      - main
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Install Dependencies'
        run: npm install
      - name: 'Perform test'
        run: npx vitest --coverage
      - name: 'Report Coverage'
        if: always() # Also generate the report if tests are failing
        uses:  davelosert/vitest-coverage-report-action@v2