name: Node Continuous Integration

on:
  push:
    branches: [ master, development ]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
      - run: npm run build